first_page/first_page/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from questions import views as question_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name='index'),
    path('services/',views.services,name='services'),
    path('pricing/',views.pricing,name='pricing'),
    
    path('question_list/', question_view.question_list),
    path('questions/', include('questions.urls')),
    
    
]

first_page/questions/urls.py
from django.urls import path
from . import views

app_name = "questions"

urlpatterns = [
    #path('', views.question_list, name='question_list'),
    path('questions/',views.question_list, name='question_list'),
    
    path('create_question/',views.create_question, name='create_question'),
    path('<pk>/', views.question_detail, name='question_detail'),
    path('edit_question/<pk>', views.edit_question, name='edit_question'),
    path('delete/<pk>', views.delete_question, name='delete_question'), 
    
    
    ]

first_page/answers/models.py
from django.db import models

# Create your models here.

first_page/questions/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
# Create your models here.

class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255,null=True,default='')
    description = RichTextField(blank=True,null=True)
    #tags = ArrayField(models.CharField(max_length=255,unique=False,blank=True),unique=False,blank=True,default=list)
    
    
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    
    
    class Meta:
        ordering = ["-created_at","-updated_at"]
    
    def __str__(self):
        return self.title
    
    
    
    

first_page/questions/forms.py
from django import forms
from . import models

#why do we need this?
#for validating forms
class QuestionForm(forms.ModelForm):
    #this is why we need meta:cause we want to validate some optional parts in models.py 
    class Meta:
        model = models.Question
        fields = ['title','description']
        
    #after that we use this class in views.py for validating

first_page/answers/views.py
from django.shortcuts import render

# Create your views here.

first_page/first_page/views.py
from django.shortcuts import render,redirect

def index(request):
   return render(request,"first_page/index.html")

def services(request):
   return render(request,"first_page/services.html")

def pricing(request):
   return render(request,"first_page/pricing.html")

first_page/questions/views.py
from django.shortcuts import render,get_object_or_404
from . import models,forms
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required



def question_list(request):
    questions = models.Question.objects.all()
    return render(request,'questions/question_list.html',{'questions': questions})



def question_detail(request, pk):
    question = get_object_or_404(models.Question, pk=pk)
    return render(request, 'questions/question_detail.html', {
        'question': question,
    })


@login_required
def create_question(request):
    form = forms.QuestionForm()
    if request.method == "POST":
        form = forms.QuestionForm(request.POST)
        if form.is_valid:
            question = form.save(commit=False)
            question.author = request.user
            question.save()
            messages.success(request, "Question created successfully")
            return HttpResponseRedirect(reverse_lazy('questions:question_detail', kwargs={'pk': question.pk}))
    return render(request, 'questions/question_form.html', {'form': form})


@login_required
def edit_question(request, pk):
    question = get_object_or_404(models.Question, pk=pk)
    form_class = forms.QuestionForm
    form = form_class(instance=question)
    if request.method == "POST":
        form = form_class(request.POST, instance=question)
        if form.is_valid:
            form.save()
            messages.success(request, "Question updated successfully")
            return HttpResponseRedirect(reverse_lazy('questions:question_detail', kwargs={'pk': question.pk}))
    return render(request, 'questions/question_form.html', {
        'form': form,
        'question': question
    })


@login_required
def delete_question(request, pk):
    question = get_object_or_404(models.Question, pk=pk)
    question.delete()
    messages.success(request, "Question deleted")
    return HttpResponseRedirect(reverse_lazy('questions:question_list'))

first_page/questions/templates/questions/question_detail.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load question_extras %}

{% block title %} {{ question.title }} {% endblock title %}

{% block content %}

<div>
    {{ block.super }}
    <br>
    <article>
        <h2 class="text-info">{{ question.title }}</h2>
        <ul class="nav nav-tabs" >

          {% if user.is_authenticated %}
              <hr>
              <li class="nav-item">
                  <a class="nav-link active bg-info text-white" href="{% url 'questions:create_question' %}">Ask a Question</a>
                </li>
              {% endif %}
              {% if user == question.author %}
                <li class="nav-item">
                  <a class="nav-link active bg-info text-white" href="{% url 'questions:edit_question' pk=question.pk %}">Edit Question</a>
                </li>
          {% endif %}

        </ul>
        <div class="callout secondary">
            {{ question.body|markdown_to_html }}
        </div>
    </article>
{#    <ul class="nav nav-tabs" >#}
{##}
{#      {% if user.is_authenticated %}#}
{#      <hr>#}
{#      <li class="nav-item">#}
{#          <a class="nav-link active bg-info text-white" href="{% url 'questions:create_question' %}">Ask a Question</a>#}
{#        </li>#}
{#      {% endif %}#}
{#      {% if user == question.author %}#}
{#        <li class="nav-item">#}
{#          <a class="nav-link active bg-info text-white" href="{% url 'questions:edit_question' pk=question.pk %}">Edit Question</a>#}
{#        </li>#}
{#    {% endif %}#}
{##}
{#    </ul>#}
</div>
  
{% endblock content %}

first_page/questions/templates/questions/question_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
All Questions {{ block.super }}
{% endblock title %}

{% block content %}
{{ block.super }}

{%  for question in questions %}
<br>
<div class="card my-6 border-info">
    <div class="card-body">
        <div>
            <div class="text-secondary text-right">By: {{ question.author }} 
                    - {{ question.created_at|date:"j F, Y" }}</div>
            <a class="text-info card-title responsive-font-size h5" 
            href="{% url 'questions:question_detail' pk=question.pk%}">
            {{ question.title }}</a>

        <hr>
        {% if question.body|wordcount <= 30 %}
        <p class="card-text">{{ question.body }}</p>
        {% else %}
            {{ question.body|truncatewords:30 }}
            <a href="{% url 'questions:question_detail' pk=question.pk %}" class="card-link">Read More</a>
        {% endif %}
    </div>
    </div>
</div>
{% endfor %}

{% endblock  %}

first_page/templates/base.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- SEO Meta Tags -->
    <meta name="description" content="Create a stylish landing page for your business startup and get leads for the offered services with this HTML landing page template.">
    <meta name="author" content="Inovatik">

    <!-- OG Meta Tags to improve the way the post looks when you share the page on LinkedIn, Facebook, Google+ -->
	<meta property="og:site_name" content="" /> <!-- website name -->
	<meta property="og:site" content="" /> <!-- website link -->
	<meta property="og:title" content=""/> <!-- title shown in the actual shared post -->
	<meta property="og:description" content="" /> <!-- description shown in the actual shared post -->
	<meta property="og:image" content="" /> <!-- image link, make sure it's jpg -->
	<meta property="og:url" content="" /> <!-- where do you want your post to link to -->
	<meta property="og:type" content="article" />

    <!-- Website Title -->
    <title>{% block title %}{% endblock %}</title>
    {% block css %}{% endblock %}
   
    <!-- Styless -->
    <link href=s"https://fonts.googleapis.com/css?family=Raleway:400,400i,600,700,700i&amp;subset=latin-ext" rel=s"stylesheet">
    <link href=" {% static 'first_page/css/bootstrap.css' %} " rel="stylesheet">
    <link href=" {% static 'first_page/css/fontawesome-all.css' %} " rel="stylesheet">
    <link href=" {% static 'first_page/css/swiper.css' %} " rel="stylesheet">
	<link href=" {% static 'first_page/css/magnific-popup.css'%} " rel="stylesheet">
	<link href=" {% static 'first_page/css/styles.css'%} " rel="stylesheet">
	
	<!-- Favicon  -->
    <link rel="icon" href="{% static 'first_page/images/favicon.png' %} ">

  
</head>
<body data-spy="scroll" data-target=".fixed-top">
    
    <!-- Preloader -->
	<div class="spinner-wrapper">
        <div class="spinner">
            <div class="bounce1"></div>
            <div class="bounce2"></div>
            <div class="bounce3"></div>
        </div>
    </div>
    <!-- end of preloader -->
    

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
        <!-- Text Logo - Use this if you don't have a graphic logo -->
        <!-- <a class="navbar-brand logo-text page-scroll" href="index.html">prototype1</a> -->

        <!-- Image Logo -->
        <a class="navbar-brand logo-image" href="{% static 'first_page\index.html' %} "><img src=" {% static 'first_page/images/logo.svg'%}" alt="alternative"></a>
        
        <!-- Mobile Menu Toggle Button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-awesome fas fa-bars"></span>
            <span class="navbar-toggler-awesome fas fa-times"></span>
        </button>
        <!-- end of mobile menu toggle button -->

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link page-scroll" href="{%url  'index' %}">خانه</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link page-scroll" href="{%url 'services'%}">خدمات</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link page-scroll" href="{%url 'pricing'%}"> خدمات ویژه و قیمت</a>

                <!-- Dropdown Menu -->          
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle page-scroll" href="#about" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false">اعضا</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="terms-conditions.html"><span class="item-text">
                        ثبت نام</span>
                        </a>
                        <div class="dropdown-items-divide-hr"></div>
                        <a class="dropdown-item" href="privacy-policy.html"><span class="item-text">ورود
                        </span></a>
                    </div>
                </li>
                <!-- end of dropdown menu -->

                <li class="nav-item">
                    <a class="nav-link page-scroll" href="#contact">برقراری تماس با ما</a>
                </li>
            </ul>
            <span class="nav-item social-icons">
                <span class="fa-stack">
                    <a href="#your-link">
                        <i class="fas fa-circle fa-stack-2x facebook"></i>
                        <i class="fab fa-facebook-f fa-stack-1x"></i>
                    </a>
                </span>
                <span class="fa-stack">
                    <a href="#your-link">
                        <i class="fas fa-circle fa-stack-2x twitter"></i>
                        <i class="fab fa-twitter fa-stack-1x"></i>
                    </a>
                </span>
            </span>
        </div>
    </nav> <!-- end of navbar -->
    <!-- end of navigation -->

    <br>
    <br>
    
    
{%block content%}



{% endblock %}
 



 
    <br>
    <br> 
    <br>
    <br> 
    <br>
    <br>
    <!-- Footer -->
    <div class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="footer-col">
                        <h4>About Evolo</h4>
                        <p>We're passionate about offering some of the best business growth services for startups</p>
                    </div>
                </div> <!-- end of col -->
                <div class="col-md-4">
                    <div class="footer-col middle">
                        <h4>Important Links</h4>
                        <ul class="list-unstyled li-space-lg">
                            <li class="media">
                                <i class="fas fa-square"></i>
                                <div class="media-body">Our business partners <a class="turquoise" href="#your-link">startupguide.com</a></div>
                            </li>
                            <li class="media">
                                <i class="fas fa-square"></i>
                                <div class="media-body">Read our <a class="turquoise" href="terms-conditions.html">Terms & Conditions</a>, <a class="turquoise" href="privacy-policy.html">Privacy Policy</a></div>
                            </li>
                        </ul>
                    </div>
                </div> <!-- end of col -->
                <div class="col-md-4">
                    <div class="footer-col last">
                        <h4>Social Media</h4>
                        <span class="fa-stack">
                            <a href="#your-link">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-facebook-f fa-stack-1x"></i>
                            </a>
                        </span>
                        <span class="fa-stack">
                            <a href="#your-link">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-twitter fa-stack-1x"></i>
                            </a>
                        </span>
                        <span class="fa-stack">
                            <a href="#your-link">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-google-plus-g fa-stack-1x"></i>
                            </a>
                        </span>
                        <span class="fa-stack">
                            <a href="#your-link">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-instagram fa-stack-1x"></i>
                            </a>
                        </span>
                        <span class="fa-stack">
                            <a href="#your-link">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-linkedin-in fa-stack-1x"></i>
                            </a>
                        </span>
                    </div> 
                </div> <!-- end of col -->
            </div> <!-- end of row -->
        </div> <!-- end of container -->
    </div> <!-- end of footer -->  
    <!-- end of footer -->


    <!-- Copyright -->
    <div class="copyright">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p class="p-small">Copyright © 2020 <a href="https://inovatik.com">Inovatik</a> - All rights reserved</p>
                </div> <!-- end of col -->
            </div> <!-- enf of row -->
        </div> <!-- end of container -->
    </div> <!-- end of copyright --> 
    <!-- end of copyright -->
    
    	
    <!-- Scripts -->
    <script src=" {% static 'first_page/js/jquery.min.js' %} "></script> <!-- jQuery for Bootstrap's JavaScript plugins -->
    <script src="{% static 'first_page/js/popper.min.js' %} "></script> <!-- Popper tooltip library for Bootstrap -->
    <script src="{% static 'first_page/js/bootstrap.min.js' %} "></script> <!-- Bootstrap framework -->
    <script src="{% static 'first_page/js/jquery.easing.min.js' %}  "></script> <!-- jQuery Easing for smooth scrolling between anchors -->
    <script src=" {% static 'first_page/js/swiper.min.js'%}"></script> <!-- Swiper for image and text sliders -->
    <script src="{% static 'first_page/js/jquery.magnific-popup.js' %} "></script> <!-- Magnific Popup for lightboxes -->
    <script src="{% static 'first_page/js/validator.min.js' %} "></script> <!-- Validator.js - Bootstrap plugin that validates forms -->
    <script src="{% static 'first_page/js/scripts.js' %} "></script> <!-- Custom scripts -->
</body>
</html>

first_page/templates/layout.html
<!DOCTYPE html>
{% load widget_tweaks %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    {% block css %}{% endblock %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
    {% if user.is_authenticated %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <a class="navbar-brand" href="{% url 'questions:question_list' %}">
            <img 
            alt="Home" style="width:38px;height:33px;"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
        <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link " href="{% url 'questions:question_list' %}">Home </a>
        </li>
        <li class="nav-item">
                <a class="nav-link" href="{% url 'questions:create_question' %}">Ask a Question</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ user.username }}
            </a>
            <div class="dropdown-menu bg-info" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Profile</a>
            <a class="dropdown-item" href="{% url 'logout' %}"><span class="fas fa-sign-in-alt"></span> Logout</a>
            </div>
        </li>
        </ul>
    </div>
    </nav>
    {% else %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
        <a class="navbar-brand" href="{% url 'questions:question_list' %}">
            <img  
            alt="Home" style="width:38px;height:33px;"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signup' %}"><span class="fas fa-user"></span> Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}"><span class="fas fa-sign-in-alt"></span> Login</a>
                </li>
            </ul>
        </div>
    </nav>

    {% endif %}
    <div>
        {% if messages %}
            {% for message in messages %}
            <div data-alert class="alert alert-info alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
               <strong> {{ message }} </strong>
            </div>
            {% endfor %}
        {% endif %}

        {% block content %}{% endblock %}
    </div>
    <footer class="footer">
        <hr/>
        <div>
            <p>Transo</p>
        </div>
    </footer>
</div>
</body>
</html>

first_page/templates/questions/questions.html
{% extends 'base.html' %}

{% block content%}

{% endblock %}